### ISSUE TITLE
MySql   qx::dao::create_table error

### ISSUE THREAD

**Issue by xiaocai123123** [QxOrm/QxOrm#121]
Hello, I have a problem
Failed to create table using MySQL When using QString as the primary key
The code is as follows

**Step1**
struct Technology
{
		QString sN;
		double cuttingSpeed;
		double cuttingPower;
		double cuttingHeight;
		double cuttingGasPressure;
		double cuttingFocus;
};
QX_REGISTER_PRIMARY_KEY(lbl::Technology, QString)

namespace qx {
	template <> void register_class(QxClass<lbl::Technology>& t)
	{
		t.setName(lbl::Technology_SName);
		t.setKey(lbl::Technology_SKey);
		t.id(&lbl::Technology::sN, lbl::DeviceParameter_ID);
		t.data(&lbl::Technology::cuttingSpeed, lbl::Technology_CuttingSpeed);
		t.data(&lbl::Technology::cuttingPower, lbl::Technology_CuttingPower);
		t.data(&lbl::Technology::cuttingHeight, lbl::Technology_CuttingHeight);
		t.data(&lbl::Technology::cuttingGasPressure, lbl::Technology_CuttingGasPressure);
		t.data(&lbl::Technology::cuttingFocus, lbl::Technology_CuttingFocus);

		t.setPropertyBag(lbl::Property_ClassType, (int)lbl::ClassType::Technology);
	}
}
**Step2**
QSqlError error = qx::dao::create_table<Technology>(&mSqlDb);

When executing create_table,The following error occurs:
BLOB/TEXT column 'SN' used in key specification without a key length 
QMYSQL: Unable to execute query

I know that MySQL does not supports TEXT as the primary key, but the type for the QString map is TEXT. How can i solve this problem?

**Comment by QxOrm** [comment]
Hello,

**qx::dao::create_table<T>** is designed to create quick and dirty schema with SQLite database.
This is written in the documentation here : [https://www.qxorm.com/qxorm_en/manual.html#manual_470](https://www.qxorm.com/qxorm_en/manual.html#manual_470)

Because you use MySQL, you should see this warning in your logs : 
`QString sWarningMsg = "-- WARNING -- the function qx::dao::create_table<T>() can be used only with a SQLite database to create examples or prototypes, for other databases, it is recommended :";
sWarningMsg += "\n\t - to use QxEntityEditor application and its DDL SQL database schema export plugin ;";
sWarningMsg += "\n\t - or to manage the database schema with an external tool provided by the SGBD (SQLite Manager for SQLite, pgAdmin for PostgreSQL, MySQL Workbench for MySQL, etc...) ;";
sWarningMsg += "\n\t - or to generate database schema using the introspection engine of QxOrm library : go to 'https://www.qxorm.com/qxorm_en/faq.html#faq_230' web page for more details.";`

However, if QString as TEXT is your only issue, you could try to change the default SQL type like this : 
`namespace qx {
template <> void register_class(QxClasslbl::Technology& t)
{
   qx::IxDataMember * pDataMember = t.id(&lbl::Technology::sN, lbl::DeviceParameter_ID);
   pDataMember->setSqlType("MY_SQL_TYPE");
}`

**Comment by xiaocai123123** [comment]
Sincerely thank you for your your patience！I'll do what you suggest！
