### ISSUE TITLE
qxFetchAll() Bug @ qx::IxPersistable objects

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#20]
Hello,
I'm trying to use the static` qxFetchAll() `function for a class which is derived from `QObject` and `qx::IxPersistable`. Unfortunately a seg. fault occurs when the application tries to access the `isValid()` function of a nullptr `QVariant`:
![grafik](https://user-images.githubusercontent.com/21241672/71971049-12852980-320a-11ea-97fa-d4d1f5529e39.png)
You can test this easily by inheriting `TestQtProperty` class from `public qx::IxPersistable`, add the `QX_PERSISTABLE_HPP(TestQtProperty)` and `QX_PERSISTABLE_CPP(TestQtProperty)`
 makros and call `auto lst = qx::IxPersistable::qxFetchAll("TestQtProperty");` in your `testQtProperty() `function.

**Comment by QxOrm** [comment]
Hello,
Yes I know this issue (but you are the first one to report it :) ).
The problem comes from static_cast and multiple inheritance.
There is the same issue with QxService module when your classes use multiple inheritance.

This project could help to fix the issue : https://github.com/bytemaster/Boost.DynamicAny/blob/master/include/boost/dynamic_any.hpp
But I don't know if I will use it or not.
Anyway, I have to find a way to fix it.

**Comment by QxOrm** [comment]
Could you please test with latest source code ?
I think I have fixed the issue.

**Comment by ChrizzyM87** [comment]
Yes! You have :)
Thank you!!
