### ISSUE TITLE
Custom data type as Q_PROPERTY bug!?

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#21]
Hello,
I would like to use custom datatypes (e.G. `cv::Mat`), register them via `Q_PROPERTY` mechanism (to ensure access via getters/setters) and persist them. I implemented serialization functions as described in the [manual](https://www.qxorm.com/qxorm_en/manual.html#manual_460). If I do **not** use `Q_PROPERTY` and instead register via `t.data(&DB::PersonDesc::m_img, "img"); ` the `toJson()` and `fromJson()` functions are called and everything works fine. But If I register via `Q_PROPERTY` conversion functions are not called and the image is not persisted.

I tried to fix this by registering `cv::Mat `to the Qt meta system and I got rid of the "unregistered datatype" warning, but problems still remains.
Best regards, Christoph

**Comment by QxOrm** [comment]
> I tried to fix this by registering cv::Mat to the Qt meta system and I got rid of the "unregistered datatype" warning, but problems still remains.
Yes this is what you have to do : you need to register correctly your type in the Qt meta engine to convert to/from variant.

**Comment by ChrizzyM87** [comment]
Conversion to and from `QVariant` works perfectly.
```
cv::Mat testImg = cv::Mat::zeros(600, 800, CV_8UC3);
QVariant tV;
tV.setValue(testImg);
cv::Mat testImg2 = tV.value<cv::Mat>();
```
But I'm wondering how.. because my to/fromVariant() functions are not called. Mh.. guess I need to dig deeper.

**Comment by QxOrm** [comment]
When you register a property as Q_PROPERTY in QxOrm context, your specialized methods _QxConvert_ToJson_ and _QxConvert_FromJson_ will be not called : this is normal.

What is called is your getter/setter defined in Q_PROPERTY (and the getter/setter convert to/from QVariant automatically).
To define correctly a Qt custom type : https://doc.qt.io/qt-5/custom-types.html

Your issue seems to be more why the QVariant is not converted to JSON.
Maybe the anwser is here, [class QJsonValue, method QJsonValue](https://doc.qt.io/qt-5/qjsonvalue.html#fromVariant) : 

> For all other QVariant types a conversion to a QString will be attempted. If the returned string is empty, a Null QJsonValue will be stored, otherwise a String value using the returned QString.

So I think you need to find a way to convert your custom type to QString to be able to see it in the generated JSON stream.
You should ask in a Qt forum for more details, because this is a pure Qt issue.

**Comment by QxOrm** [comment]
I think the solution is : [QMetaType::registerConverter](https://doc.qt.io/qt-5/qmetatype.html#registerConverter).

There is a good article here which explains what you can do with a Qt custom type : https://www.codeproject.com/Tips/1277932/Strongly-Typed-Identifiers-with-Qt

The interesting part for you is : 

> class ElementId { public: QString toString() const { return QString::number(m_value); } };
QMetaType::registerConverter<ElementId, QString>(&ElementId::toString);

Which allows you to convert your custom type to/from QString.

This is not as great as QxOrm library specialization because you can't create complex structure in your JSON, but at least you can see your data (serialized as QString).
I don't know if there is a way to register like this some converters to/from QJsonValue, but if no ==> then I think it would be a good feature request to put in [Qt JIRA issue tracker](https://bugreports.qt.io/projects/QTBUG/issues/QTBUG-81253?filter=allopenissues).

**Comment by ChrizzyM87** [comment]
YES! It worked out! Thank you so much for your tips!
I created a class Frame, which is derived from cv::Mat and adds to / from String functions.
```
static Frame fromString(const QString &str);
QString toString() const;
```
Then I registered the type and converters to the Qt meta system:
```
Q_DECLARE_METATYPE(LaBP::Frame)
...
qRegisterMetaType<LaBP::Frame>("LaBP::Frame");
QMetaType::registerConverter<LaBP::Frame, QString>(&LaBP::Frame::toString);
QMetaType::registerConverter<QString, LaBP::Frame>(&LaBP::Frame::fromString);
```

I think there must be a more efficient way to do it e.G. by not using QString and instead use QDataStream or boost serialization, but for now this is a good solution.

**Comment by QxOrm** [comment]
Great !
