### ISSUE TITLE
Get JSON from MongoDb

### ISSUE THREAD

**Issue by Andreychikov-Vasiliy** [QxOrm/QxOrm#30]
Possibly, it will be good option to load document or even some field of document as QJsonObject? For further usage them in service or qml.

**Comment by Andreychikov-Vasiliy** [comment]
Wow, I found that it is already possible, using *QVariantMap* mapping:
```c++
QVariantMap m_group;
```

**Comment by QxOrm** [comment]
Hello,

Yes this is possible and it is explained in the QxOrm manual here : 
https://www.qxorm.com/qxorm_en/manual.html#manual_9923

If you prefer **QJsonValue** instead of **QVariantMap**, here is how to do : 

// Call a custom query with cursor and get JSON response as QJsonValue
qx_query customQueryCursor("cursor", "{ \"find\": \"author\", \"filter\": { } }");
qx::dao::call_query(customQueryCursor);
QJsonValue json;
qx::cvt::from_string(customQueryCursor.response().toString(), json);
// Here the 'json' instance contains the MongoDB database result as QJsonValue type...
