### ISSUE TITLE
Bug in Release mode with qx::IxPersistable derived classes

### ISSUE THREAD

**Issue by Christoph-LaBP** [QxOrm/QxOrm#32]
Hello,
as you probably know, I'm using QxORM with MongoDB and my DB classes are derived by qx::IxPersistable. I implemented several test cases for e.G. inserting / updating / fetching objects. One test case is e.G. insert object, fetch object and compare fetched and inserted objects. Usually all tests are passed successfully, but if I compile the application in release mode and run it by e.G. pressing CTRL+R in QtCreator or by running the application from command line, tests which process objects containing double attributes fail. If I run the application by pressing F5, still compiled in release mode, all tests run successfully.

I observed that in the cases the tests fail, double values are reduced to int values. Following is the toJson() output of e1 (the inserted object) and e3 (the fetched object):
```
e1:	{
    "auRegVec": "17,,12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,200.11",
    "containerId": "",
    "iProcessed": false,
    "id": "qx_oid:5e7b7cf193a7a536ab198047",
    "landmarkConfidence": 0.98,
    "pitch": 99.11,
    "tspCreated": "2020-03-25T16:46:57",
    "yaw": 90,
    "z": 5.01
}
e3:	{
    "auRegVec": "17,,12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,200.11",
    "containerId": "",
    "iProcessed": false,
    "id": "qx_oid:5e7b7cf193a7a536ab198047",
    "landmarkConfidence": 0,
    "pitch": 99,
    "tspCreated": "2020-03-25T16:46:57",
    "yaw": 90,
    "z": 5
}
```
As you can see the confidence, pitch and z values do not match. Problem seems not to be the fetch fct. They are already stored incorretly in MongoDB.
You got any clue what causes this?

Best regards,
Christoph

**Comment by QxOrm** [comment]
Hello,

_double_ management in C++ is always a mess.

You say that it is already stored incorrectly in MongoDB.
The function which convert your double type to JSON is in file **./inl/QxConvert/QxConvert_ToJson.inl** (so maybe you could add some logs here ? ) :

```
template <> struct QxConvert_ToJson< double > {
static inline QJsonValue toJson(const double & t, const QString & format)
{ Q_UNUSED(format); return QJsonValue(t); } };
```

As you can see, there is nothing special, because QJsonValue has a constructor with a _double_ parameter.

Maybe you have some diff between F5, CTRL+R, debug mode, etc... because : 
- have you several Qt versions installed on your dev environment ? If yes, are you sure you call the good one each time ?

Maybe you could ask also in a Qt forum ?
Or maybe the problem is inside the MongoDB C++ driver ?

For now, sorry I can't say more about that.
But I'm am interested if you find a solution to this issue :)

**Comment by ChrizzyM87** [comment]
Hello,
thanks for your help! I got only one installed Qt version, so that could not be the issue.
I enabled the logs and the JSON which is sent is correct:
```
[QxOrm] sql query (total: 1.37 ms, db_exec: 1.13 ms) : MongoDB insert one 'Face' :
{
    "auRegVec": "17,,12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,200.11",
    "containerId": "",
    "landmarkConfidence": 0.98,
    "pitch": 99.11,
    "tspCreated": "2020-03-27T11:55:10",
    "yaw": 90.31999969482422,
    "z": 5.01
}
```
So conversion to JSON could not be the problem. 
I changed a double type to a float type, but problems is the same.

I assume that the JSON String is directly forwarded to MongoDB C++ driver which sends it to MongoDB? But in this case I have no idea how starting with F5 / CTRL+R can make a difference.
Does QxOrm / MongoDB C++ driver send any type information to MongoDB or is it just the JSON which is parsed?

**Comment by QxOrm** [comment]
If the JSON sent to MongoDB is correct, then issue should be in : 
- in the C++ MongoDB driver (have you several versions of this driver on your dev environement ?)
- or in MongoDB database

> Does QxOrm / MongoDB C++ driver send any type information to MongoDB or is it just the JSON which is parsed?
There is no type information, so MongoDB database parses the JSON (actually this is BSON) and inserts it in database.

**Comment by ChrizzyM87** [comment]
Mhh... really strange! I did have different MongoDB drivers installed, but ldd output was the same for the different application starting methods. Now I deleted the unnecessary mongoDB drivers to make sure that only one is used - problem remains and in Debug mode everything works fine.
I don't think that the MongoDB itself can cause the problem, because in Debug mode everything works. Mhh...
UPDATE:
I figured out that everything works perfect (regardless how I start the application) on machines were mongo environment (server/client applications and libaries) is not installed. Ich checked via ldd if my application, QxOrm or the MongoC++ driver has different linkings, but everything seems to be the same.

**Comment by QxOrm** [comment]
I don't know if it could be the issue, but depending on the country, you can have different separator for decimal. It could be , or . 
I don't know if MongoDB is sensible about that.

Have you tried to ask for your issue in a MongoDB or MongoDB C++ driver forum ?

**Comment by ChrizzyM87** [comment]
Different separators cannot be the issue, i logged transactions via MongoDB. The incoming BSON string does contain double values with dot as decimal separator in both cases, but in the case were the issue occurs, it looks like `yaw: 90.0,`, but it has to be `yaw: 90.123487324,`.
I asked some collegues for advise, and will ask in a MongoDB C++ driver forum. I will let you know!

**Comment by Christoph-LaBP** [comment]
Can you tell me where QxOrm passes the BSON string to MongoDB C++ library?

**Comment by QxOrm** [comment]
File ./src/QxDao/QxMongoDB/QxMongoDB_Helper.cpp :
For a simple insert, method QSqlError QxMongoDB_Helper::QxMongoDB_HelperImpl::insertOne_ : 

The BSON is initialized like this : 

`qx_scoped_wrapper<bson_t> doc(toStdString(json));`

Then it is passed to the MongoDB C++ driver like this : 

`bool ok = mongoc_collection_insert_one(coll.collection->get(), doc.get(), (opts ? opts->get() : NULL), (reply ? reply->get() : NULL), (& bsonError));`

**Comment by Christoph-LaBP** [comment]
This seems to be a problem of libbson, which only occurs in Qt environments. I created an issue:
https://jira.mongodb.org/browse/CDRIVER-3626
I wonder that the problem did not show up already at your side. Maybe it's really specific and limited to Ubuntu 16.04. Is the minimal example working for you, and which OS are you using?

**Comment by QxOrm** [comment]
Thx for the info.
I have several environments to test QxOrm library, but my main dev env is Windows + MSVC 2012 + Qt 5.1.1 (yes I know this is an old version).
I have also : 
- Win + MSVC 2017 + Qt 5.9
- Ubuntu 12 + GCC 4.9 + Qt 5.1.1
- Mac OS X + clang + Qt 5.1.1

I will test your minimal example from your MongoDB JIRA ASAP.

Maybe you could ask also on the official Qt forum to see if someone know what QApplication could change to produce the issue ?

**Comment by QxOrm** [comment]
FYI I tested on this environment : Win 10, MSVC 2012, Qt 5.1.1, bson 1.10.2.
In Debug and Release mode, I have exactly the same output : 
`{ "d" : { "$numberDouble" : "1.9870000000000001" } }`

So it seems ok on my dev env.

**Comment by Christoph-LaBP** [comment]
This fixes the issue:
```
const char *result = setlocale(LC_NUMERIC, "C");
if (!result)
    fprintf(stderr, "Warning: cannot change LC_NUMERIC to 'C'!");
```
Must be included after creating QCoreApplication to set printf output numeric dots instead commas. Thanks to aha_1980! ( https://forum.qt.io/topic/114725/mongo-c-driver-loosing-decimal-digits-in-qt-application/3 )

**Comment by QxOrm** [comment]
Great ! Thx for the info !
