### ISSUE TITLE
Performance of qx::dao::save is very poor

### ISSUE THREAD

**Issue by tqtiimy** [QxOrm/QxOrm#33]
hello
save is very slow when inserting large amounts of data, and how to Improve Insert Performance ，thanks

**Comment by QxOrm** [comment]
Hello,

If you know that you are just inserting : use **qx::dao::insert** instead of **qx::dao::save**

**qx::dao::save** will check if it has to update or insert the instance, this is why it is slower than **qx::dao::insert**.

Moreover, if you want to insert a list of items to database, you can pass a **QList** (or other container) in **qx::dao::insert**.
All supported containers are in the manual here : https://www.qxorm.com/qxorm_en/manual.html#manual_390

There is also some specific database process to insert faster.
For example, PostgreSQL has a specific batch process to insert quickly a lot of data.
To use it, you have to create the query yourself, then call : **qx::dao::call_query**
Manual here : https://www.qxorm.com/qxorm_en/manual.html#manual_9923

**Comment by tqtiimy** [comment]
thanks
