### ISSUE TITLE
Modifying the table name cannot take effect on the operation. After one operation

### ISSUE THREAD

**Issue by ZileSong** [QxOrm/QxOrm#73]
The Code
```
CustomEntity data;

// Execute insert operation once
qx::dao::insert(data, db_connect);

//Modify table name
 qx::QxClassX::getClass("CustomEntity ")->setName("customentity_test");

// Execute insert operation again
qx::dao::insert(data, db_connect);
// Still insert into the unmodified table
// No operation on customentity_test

//But it works on operations that have not been performed
//For example
qx::dao::Update(data, db_connect);
//Updated table customentity_test
```

Why is this？
After another operation, is some data cached？
Look forward to your answer.

**Comment by QxOrm** [comment]
Hello,

Yes, there is a cache in the **QxSqlQueryBuilder.h** file : see the macros _QX_SQL_BUILDER_INIT_FCT_ and _QX_SQL_BUILDER_INIT_FCT_WITH_RELATION_.

I don't know why you want to change a table name dynamically, but this has not been designed for that.

**Comment by ZileSong** [comment]
Thank you for your reply.
In the case of split tables, the table structure is the same, but the table name will change.Have you not considered this situation？

**Comment by QxOrm** [comment]
If you have several tables with the same structure, I would recommend to use **[inheritance](https://www.qxorm.com/qxorm_en/manual.html#manual_440)** instead of trying to change dynamically table names.

So you could imagine to have a base class which contains all properties you want to share with several classes.
Then for each table, you write a specific class which inherits of this base class.
The qx::register_class<T> of the inherited class is just : _t.setName("my_table_name");_
All properties registered in the base class are automatically mapped.

Just be careful with relationships : you have to register the relationships in the inherited classes, because relationships don't supprt inheritance.

**Comment by ZileSong** [comment]
Thank you for your suggestion.
Unfortunately, I add a table with the same structure every day.
Anyway, thank you for your reply.

**Comment by QxOrm** [comment]
You can also try to change the generated SQL yourself using some callbacks.
For example, you can create your own SQL generator (interface qx::dao::detail::IxSqlGenerator), then implement this method : 
`virtual void onBeforeSqlPrepare(IxDao_Helper * pDaoHelper, QString & sql) const;`

The parameter _QString & sql_ allows to do some replaces before executing the SQL : so you could write something like : 
`sql = sql.replace(" old_table_name ", " new_table_name ");`

The _pDaoHelper_ parameter allows to know on which class you are executing your replace.

So for example, if you use SQLite database, then create a class which inherits from : _qx::dao::detail::QxSqlGenerator_SQLite_.
Then, implement the method : _onBeforeSqlPrepare_

You can register your SQL generator like this : 
```
   qx::dao::detail::IxSqlGenerator_ptr pSqlGenerator;
   pSqlGenerator.reset(new MyGenerator());   
   qx::QxSqlDatabase::getSingleton()->setSqlGenerator(pSqlGenerator);   
```
